# Generated by Django 3.2.14 on 2022-07-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220708_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
