# Generated by Django 3.2.14 on 2022-07-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220709_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Позиция'),
        ),
    ]
