# Generated by Django 4.0.6 on 2022-07-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_order_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Позиция'),
        ),
    ]
